### PR TITLE
Implemented a function to perform of revoke in a single node forcibly.

### PR DESCRIPTION
**Pull request by yuusuke**
I implemented a function to perform of revoke in a single node forcibly separately from overall revoke.
I think that this function is employed when admin wants to switch a ticket in another site.
This function is carried out by adding -f option to revoke command.

Example
booth client revoke -t ticketA -s **\* -f

### CODE REVIEW

**Comment by jjzhang** [comment]
I copied the patch here and comment inline;)

diff --git a/src/main.c b/src/main.c
index 4b48c83..9ec22b3 100644
--- a/src/main.c
+++ b/src/main.c
@@ -971,7 +971,7 @@ static int read_arguments(int argc, char **argv)
                        break;

```
            case 'f':
```
-                       if (cl.op == OP_GRANT)
-                       if (cl.op == OP_GRANT || cl.op == OP_REVOKE)
                              cl.force = 1;
                      else {
                              print_usage();

Good catch, I'll merge this part of the patch.

+int paxos_lease_release_force(pl_handle_t handle)
+{
-       struct paxos_lease *pl = (struct paxos_lease *)handle;
  +
-       if (pl->acceptor.timer2)
-               del_timer(&pl->acceptor.timer2);
-       if (pl->acceptor.timer1)
-               del_timer(&pl->acceptor.timer1);
-       if (pl->proposer.timer2)
-               del_timer(&pl->proposer.timer2);
-       if (pl->proposer.timer1)
-               del_timer(&pl->proposer.timer1);
  +
-       pl->owner = -1;
  +
- ```
    return 0;
  ```
  
  +}
  +
  static int lease_catchup(pi_handle_t handle)
  {
        struct paxos_lease *pl;
  diff --git a/src/paxos_lease.h b/src/paxos_lease.h
  index bb46ec1..6a159a7 100644
  --- a/src/paxos_lease.h
  +++ b/src/paxos_lease.h
  @@ -64,6 +64,8 @@ int paxos_lease_status_recovery(pl_handle_t handle);
  
  int paxos_lease_release(pl_handle_t handle);

+int paxos_lease_release_force(pl_handle_t handle);
+
 int paxos_lease_exit(pl_handle_t handle);

 #endif /\* _PAXOS_LEASE_H */
diff --git a/src/ticket.c b/src/ticket.c
index 61451e3..befb367 100644
--- a/src/ticket.c
+++ b/src/ticket.c
@@ -429,8 +429,10 @@ int revoke_ticket(char *ticket, int force)
        }

```
    if (force) {
```

 static int lease_catchup(pi_handle_t handle)
 {
        struct paxos_lease *pl;
diff --git a/src/paxos_lease.h b/src/paxos_lease.h
index bb46ec1..6a159a7 100644
--- a/src/paxos_lease.h
+++ b/src/paxos_lease.h
@@ -64,6 +64,8 @@ int paxos_lease_status_recovery(pl_handle_t handle);

 int paxos_lease_release(pl_handle_t handle);

+int paxos_lease_release_force(pl_handle_t handle);
+
 int paxos_lease_exit(pl_handle_t handle);

 #endif /\* _PAXOS_LEASE_H */
diff --git a/src/ticket.c b/src/ticket.c
index 61451e3..befb367 100644
--- a/src/ticket.c
+++ b/src/ticket.c
@@ -429,8 +429,10 @@ int revoke_ticket(char *ticket, int force)
        }

```
    if (force) {
```
-               paxos_lease_release_force(tk->handle);
              pcmk_handler.store_ticket(tk->id, -1, 0, 0);
              pcmk_handler.revoke_ticket(tk->id);
-               return BOOTHC_RLT_SYNC_SUCC;
      }

However, "revoke -f" should be used when the admin has already run "grant -f" at the beginning, which means the admin didn't use the booth mechanism to manage the ticket automatically.
In the scenario as you described, the admin may want to revoke the ticket from the original site but permit the ticket being granted to another site, he should revoke the ticket first and then grant the ticket to another site, that is the suggested steps.
I think for the implication that "grant -f" and "revoke -f" should be executed conjugated, the admin may not know this. So, adding some error checking in the command line should be good;)

**Comment by yuusuke** [comment]
> However, "revoke -f" should be used when the admin has already run "grant -f" at the beginning, which means the admin didn't use the booth mechanism to manage the ticket automatically.
> In the scenario as you described, the admin may want to revoke the ticket from the original site but permit the ticket being granted to another site, he should revoke the ticket first and then grant the ticket to another site, that is the suggested steps.

For a program to work in cooperation with booth which I made, I wanted means to let a ticket switch to the site except oneself automatically.
The implementation that was the simplest to realize it was "revoke -f".
After revoke did a ticket, it is the work that is ideal for me that authority moves to other sites.

> I think for the implication that "grant -f" and "revoke -f" should be executed conjugated, the admin may not know this. So, adding some error checking in the command line should be good;)

Do you hope that you add what kind of error check?

> Good catch, I'll merge this part of the patch.

Which part will merge do?

**Comment by jjzhang** [comment]
> For a program to work in cooperation with booth which I made, I wanted means to let a ticket switch to the site except > oneself automatically.
> The implementation that was the simplest to realize it was "revoke -f".
> After revoke did a ticket, it is the work that is ideal for me that authority moves to other sites.

Ok, so what your want is another semantic of "revoke".
In current implementation, "revoke" means revoke the ticket from the orginal site, and also other sites won't try to acquire the ticket. It is just go back to the initial state.
What your wanted is to revoke the ticket from the original site, and feel free to let another site acquire the ticket automatically. Well, the first version of the revoke implementation is just like this;) However someone told me that this behavior of revoke may confuse people, so I change that to current version;)
Could you explain more about your requirements?;) And why current "reovke + re-grant" cannot work for you in your situation? 

> Do you hope that you add what kind of error check?

If the admin has used "-f" when granting the ticket to current site, he must use "-f" when revoking that ticket later on. If he didn't use "-f" in "grant", then he should not use "-f" in "revoke".

> Which part will merge do?

```
            case 'f':
```
-                       if (cl.op == OP_GRANT)
-                       if (cl.op == OP_GRANT || cl.op == OP_REVOKE)
                              cl.force = 1;
                      else {
                              print_usage();

**Comment by yuusuke** [comment]
> Could you explain more about your requirements?;) 

For the system which explained that I make it before, a function to move this ticket is necessary.
When a resource was not able to operate in sites, this system performs movement to move the ticket between sites.

> And why current "reovke + re-grant" cannot work for you in your situation?

You are right, and the purpose can be accomplished in grant + re-grant.
However, it is necessary to appoint an address to perform re-grant.
I wanted to omit processing to appoint the address.
I reconsider it to implement it once again in revoke+re-grant.

> If the admin has used "-f" when granting the ticket to current site, he must use "-f" when revoking that ticket later on. If he didn't use "-f" in "grant", then he should not use "-f" in "revoke".

I will think about this.

> Which part will merge do?
>                case 'f':
> -                       if (cl.op == OP_GRANT)
> -                       if (cl.op == OP_GRANT || cl.op == OP_REVOKE)
>                               cl.force = 1;
>                       else {
>                               print_usage();

I understood it.

**Comment by jjzhang** [comment]
Hi Yuusuke,

I considered your requirements once more, it seems that you want a "booth migrate" command, which contains "booth revoke" and "booth grant". And we may implement it like this: if the user provide a target granting site, the ticket will be there, if the user doesn't provide a target granting site, let the booth algorithm select one site to hold the ticket, just have the same semantic as your "revoke -f".

Considering the "-f" option more, I think we'd better remove it because it may introduce many confusion on how it works. My original thought is to provide the user a method to bypass booth algorithm and manage the ticket manually, so added them. For now, as the user can easily use crm_ticket in pacemaker to do this, so in booth, we needn't provide this any longer.

Any thoughts?;)

**Comment by jjzhang** [comment]
Seems we are commenting at the same time;)

**Comment by yuusuke** [comment]
Hi, Jiaju

> I considered your requirements once more, it seems that you want a "booth migrate" command, which contains "booth revoke" and "booth grant". And we may implement it like this: if the user provide a target granting site, the ticket will be there, if the user doesn't provide a target granting site, let the booth algorithm select one site to hold the ticket, just have the same semantic as your "revoke -f".

"booth migrate" matches my purpose as far as I looked.
I am glad if it is implemented.

> Considering the "-f" option more, I think we'd better remove it because it may introduce many confusion on how it works. My original thought is to provide the user a method to bypass booth algorithm and manage the ticket manually, so added them. For now, as the user can easily use crm_ticket in pacemaker to do this, so in booth, we needn't provide this any longer.

I thought in various ways, but think that I should abolish the "-f" option because how to use is complicated.

I intend to close my this pull request.
I hope for implementation of "booth migrate" instead.

Thanks,
Yuusuke

**Pull request closed without merging**
